
- hosts: all
  become: true
  tasks:
  - debug: msg="Installing docker"

  - name: "Install prereqs"
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common


  # Add docker key
  - apt_key:
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present


  # Add docker repo
  - apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
      state: present
      filename: 'docker'

  - name: "Install docker"
    apt:
      name: docker-ce
      update_cache: yes

