
- hosts: all
  become: true
  tasks:
  - debug: msg="Installing hashicorp utils"

  - name: "Install unzip"
    apt:
      name: unzip
      update_cache: yes

  - name: Get packer tarball
    get_url:
      url: 'https://releases.hashicorp.com/packer/1.0.3/packer_1.0.3_linux_amd64.zip'
      dest: /root/packer_1.0.3_linux_amd64.zip
      mode: 0755

  - name: unzip packer
    unarchive:
      src: /root/packer_1.0.3_linux_amd64.zip
      mode: 0755
      dest: /root/
      remote_src: yes

  - name: Copy packer binary into place
    copy:
      src: /root/packer
      dest: /usr/bin/packer
      mode: 0755
      remote_src: yes

  - name: Get terraform tarball
    get_url:
      url: 'https://releases.hashicorp.com/terraform/0.10.0/terraform_0.10.0_linux_amd64.zip'
      dest: /root/terraform_0.10.0_linux_amd64.zip
      mode: 0755

  - name: unzip terraform
    unarchive:
      src: /root/terraform_0.10.0_linux_amd64.zip
      mode: 0755
      dest: /root/
      remote_src: yes

  - name: Copy terraform binary into place
    copy:
      src: /root/terraform
      dest: /usr/bin/terraform
      mode: 0755
      remote_src: yes
