
- hosts: all
  become: true
  tasks:
  - debug: msg="Installing k8s client utils"

  - name: "Install curl"
    apt:
      name: curl
      update_cache: yes

  - name: Get k8s version
    command: curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
    register: k8s_version

  - debug: msg="k8s version {{ k8s_version }}"



  - name: Copy kubectl binary into place
    copy:
      src: /root/kubectl
      dest: /usr/bin/kubectl
      mode: 0755
      remote_src: yes

  # Add helm
  - name: Get helm install script
    get_url:
      url:  https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get
      dest: /root/get-helm
      mode: 0755

  - name: install helm
    command: /root/get-helm
